### ISSUE TITLE
글이 공백없이 붙어서 나옵니다.

### ISSUE THREAD

**Issue by minikupa** [ruden91/public-basecamp-skin#1]
http://web.archive.org/web/20210118003052/https://minikupa-dev.tistory.com/186
위는 제 블로그인데, 글이 공백 없이 다 붙어서 나옵니다.  tt_article_useless_p_margin 태그가 안보이던데 이 때문이 아닌가 싶습니다. 설정에서 단락 앞뒤 공백은 사용 설정해놨습니다.

**Comment by ruden91** [comment]
images 폴더 안에 있는 assets들 모두 넣어주셨나요? 현재 페이지에 아이콘도 안나오고 있는 상태라서요!

**Comment by minikupa** [comment]
네 모두 넣었습니다. 제가 임의로 [##_artivle_rep_desc_##]태그를 <div class="~~uselessmargin~~~">태그로 감싸봤더니 잘 되네요.

**Comment by ruden91** [comment]
해당 부분은 티스토리에서 html을 붙여줄 때 생성되는 태그인데 다시 한번 확인해 보겠습니다

**Comment by minikupa** [comment]
아직 해당 문제가 해결되지 않은 것 같습니다. 최신 버전을 사용하고 있는데, 아직도 그렇네요. 제 임의로 tt_article_useless_p_margin로 덮어 사용중입니다.

**Comment by ruden91** [comment]
혹시 마크다운으로 작성하셨나요??

**Comment by ruden91** [comment]
CSS 작성규칙을 좀 바꿔서 올려놓을게요

**Comment by minikupa** [comment]
아뇨. 그냥 기본모드에서 글쓰고 있습니다.

**Comment by minikupa** [comment]
죄송하지만.. 현재 버전에서 해당 문제가 해결된 것이 맞나요?

**Comment by ruden91** [comment]
![image](https://user-images.githubusercontent.com/13517699/105439002-6775cf80-5ca7-11eb-9232-fd6f39f5caa9.png)

현재 이렇게 노출되고 있는데 아직도 해당 증상이 발생하나요??

**Comment by ruden91** [comment]
![image](https://user-images.githubusercontent.com/13517699/105439187-bae81d80-5ca7-11eb-8af2-c028c349292c.png)

**Comment by minikupa** [comment]
![화면 캡처 2021-01-22 115559](https://user-images.githubusercontent.com/19676242/105439833-e3bce280-5ca8-11eb-866e-d5d5676f59a8.jpg)
현재는 .bc-markdown__inner-content .tt_article_useless_p_margin p 이렇게 설정돼있는 것 아닌가요?

**Comment by ruden91** [comment]
네 tt_article_useless_p_margin 클래스네임이 없어야합니다

**Comment by ruden91** [comment]
아이고 죄송합니다 제가 집에서 작업했던 해당 부분이 누락되어 안올라간 것 같네요ㅠㅠ

**Comment by ruden91** [comment]
다시 다운로드 한번 부탁드릴게요!ㅎ

**Comment by minikupa** [comment]
넵 감사합니다. 근데 혹시 해당 태그가 없어도, 목차가 정상적으로 나오나요?

**Comment by ruden91** [comment]
기본적으로 h2, h3 태그가 존재하지 않으면 목차가 생성되지 않아요!

**Comment by ruden91** [comment]
잠깐 코드 확인해보니까 목차 생성도 tt_article_useless_p_margin 셀렉터 포함되어있네요..ㅋㅋ 이것도 바꿔야겠어요

**Comment by ruden91** [comment]
점심먹고 반영하겠슴다 :<

**Comment by minikupa** [comment]
넵 감사합니다

**Comment by ruden91** [comment]
확인 한번 부탁드립니다

**Comment by minikupa** [comment]
제가 좀 확인이 늦었네요.. 지금 정상적으로 나오는 것 같습니다. 감사합니다.
