### ISSUE TITLE
Manage, Modify, Delete Button

### ISSUE THREAD

**Issue by ParkHyeonSeong** [ruden91/public-basecamp-skin#11]
깃헙에 있는 것들을 1개도 빠짐없이 올리고 적용을 시키면 기본 사용자에게 보여야할 관리 및 글쓰기버튼, 글페이지에서 수정 및 삭제버튼이 보이지가 않네요. 초기 기본 스킨에서 변경만 했을 뿐인데 보이지가 않아요 흑흑..

생각보다 html소스가 복잡해보이긴한데, UI/UX 부분은 매우 보기 좋고 릴리즈업데이트하신다면 더 좋은 스킨될 것 같네요 :)

+ 추가
글 페이지에서 제목과 필명다음에 어느정도 margin을 두고 글본문이 나오는게 좋을 것 같습니다!
+ 추가
문장과 문장띄어쓰기칸하고 코드블럭 칸과 문장 사이의 칸같은 newline 공백의 크기가 제각각인것 같습니다.
기본 에디터로 모두 작성하였는데, 어떤게 문제가 되는 부분일까요?

**Comment by ruden91** [comment]
기본적으로 로그인이 되어있지 않다면 관리 및 글쓰기 버튼이 노출되진 않는데 혹시 로그인 상태가 맞으신가요?
#3 혹시 해당 사항에 대한 이슈가 맞나 궁금합니다

- [ ] 글 페이지에서 제목과 필명다음에 어느정도 margin을 두고 글본문이 나오는게 좋을 것 같습니다!

Q. 문장과 문장띄어쓰기칸하고 코드블럭 칸과 문장 사이의 칸같은 newline 공백의 크기가 제각각인것 같습니다. 기본 에디터로 모두 작성하였는데, 어떤게 문제가 되는 부분일까요?
A. 모든 태그에는 margin-bottom 30px이 기본값으로 들어있습니다 칸 사이에 의도적으로 엔터로 간격을 띄우시면 기본 30px이 더 들어가는거라 사이가 너무 벌어질겁니다

해당 부분이 아니라면 혹시 스크린샷 첨부 부탁드려도 될까요 :)

**Comment by ruden91** [comment]
사이트에 들어가보니 images 안에 있는 추가적인 파일들이 누락된 것 같아요!

**Comment by ruden91** [comment]
https://oneofday.tistory.com/

assets(js, css, images)들이 누락되어서 안나오는 이슈같으니 images 폴더 안에 존재하는 모든 파일을 같이 업로드해주세요!

**Comment by ParkHyeonSeong** [comment]
스킨 삭제 후 다시 assets들 업로드된거 다시 확인하고 저장해서 진행해보았습니다.

1. 일단 글 수정삭제부분은 정상적으로 확인되었습니다.

2. 그 문장띄어쓰기 마진이 애초에 넓었군요...
스킨마다 제각각이라 참 어렵네요 ㅎㅎ 그렇다면 혹시 글 시작부분에 공백은 따로 수정계획은 없으신가요?
직접 공백을 줘야하는지 궁금합니다!

3. 혹시 관리자페이지로 이동하는 버튼이 어디쯤 위치해있을까요? 다시 적용하고 찾아봐도 보이지가 않습니다.

4. python 블록코드는 지원하는 css가 없을까요..? ㅎㅎㅎㅎ

**Comment by ruden91** [comment]
2. 글 시작 부분 여백이 너무 좁다면 다른 스킨 참고해서 반영해보겠습니다.
3. 페이지 최 하단에 배치되어 있습니다
4. 티스토리 highlight.js 설치하면 해결될 것 같습니다

**Comment by ParkHyeonSeong** [comment]
페이지 최하단에 관리자 페이지가 제가 못찾는건지 질문드립니다
![image](https://user-images.githubusercontent.com/38040655/105283565-1658d380-5bf4-11eb-9fb2-4c1845ef12d4.png)

보이지가...않습니다...!!!

**Comment by ruden91** [comment]
![image](https://user-images.githubusercontent.com/13517699/105283679-4e601680-5bf4-11eb-9aec-3ec01d212eca.png)

**Comment by ruden91** [comment]
아 관리자 페이지로 이동 말씀하시는거군요ㅋㅋ

**Comment by ruden91** [comment]
고거는 제가 따로 반영하겠습니다

**Comment by ParkHyeonSeong** [comment]
넹ㅎㅎㅎㅎ

**Comment by ParkHyeonSeong** [comment]
감사합니다 ㅠ_ㅠ
manage링크를 만들까 아주 잠깐 0.0001초 생각했습니다.
빠른 피드백 감사드립니다.

**Comment by ruden91** [comment]
저야말로 피드백주셔서 감사합니다

**Comment by ruden91** [comment]
관리자페이지로 이동하는건
![image](https://user-images.githubusercontent.com/13517699/105353563-c0efe700-5c32-11eb-80b6-b0f5f29521bb.png)

티스토리 관리자 페이지에서 해당 부분 활성화하셔야합니다
