### ISSUE TITLE
바텀바가 공중에 떠있습니다

### ISSUE THREAD

**Issue by minikupa** [ruden91/public-basecamp-skin#13]
![Screenshot_20210121-162446_Chrome.jpg](https://user-images.githubusercontent.com/19676242/105317514-a05d6800-5c05-11eb-910b-47f11330a313.jpg)
사이드바에서 아래로 스크롤 하면 바텀바가 아래에 붙어 있지 않고 떠있다가 잠시후에 내려갑니다.

스크롤 할 때 손을 떼지 않고 있으면, 떠있는 상태로 유지되네요. 모바일 웨일 브라우저, 크롬 브라우저에서 테스트 해봤습니다.

**Comment by minikupa** [comment]
A퀀텀 사용중입니다. 크롬, 웨일 뿐만 아니라 카톡 내장 브라우저, 삼성 인터넷에서도 똑같네요.

**Comment by minikupa** [comment]
https://youtu.be/5KDquU-7On8

**Comment by ruden91** [comment]
https://basecamp-sense.tistory.com/

갤럭시 a7
아이폰x
테스트 결과 해당 부분 해결된듯한데 확인 부탁드릴게요
증상 발생 안하면 내일 오전에 반영해놓을게요:)
