### ISSUE TITLE
갤럭시탭 s7에선 썸네일이 너무 크게 나옵니다.

### ISSUE THREAD

**Issue by inthegun** [ruden91/public-basecamp-skin#2]
![image](https://user-images.githubusercontent.com/64422870/104880855-a6540e80-59a3-11eb-85a6-28c41c0926a4.png)

데스크탑에선 큰 이상없으니 탭이나 휴대폰에선 조금더 작은 이미지로 나왔으면 좋겟습니다.

제가 작업한 썸네일 사이즈는 500*500 입니다.

**Comment by ruden91** [comment]
해당 부분 확인해보겠습니다

**Comment by ruden91** [comment]
내일 오전에 1.0.0-rc1
해당 사항, 내 글 목록 수정/삭제 기능 추가 반영 예정입니다 :)

**Comment by ruden91** [comment]
#4 참고해주세요!

**Comment by ruden91** [comment]
![Uploading 2021-01-18 22.30.50.gif…]()

**Comment by ruden91** [comment]
인덱스 페이지 브레이크포인트 예시
![2021-01-18 22 30 50](https://user-images.githubusercontent.com/13517699/104921648-f7342900-59dc-11eb-9382-55d7e33a6061.gif)
