### ISSUE TITLE
폰트 크기가 너무 작은 것 같습니다

### ISSUE THREAD

**Issue by minikupa** [ruden91/public-basecamp-skin#21]
![Screenshot_20210122-190218_Whale.jpg](https://user-images.githubusercontent.com/19676242/105476779-5e572380-5ce4-11eb-8424-02420e4f6606.jpg)
우선 너무 많이 이슈를 남겨 죄송합니다.. 별게 아니고 모바일에서의 폰트 크기가 너무 작은 것 같습니다. PC에서 폰트 크기는 적당하지만, 모바일에선 너무 작다고 느껴지네요.

**Comment by ruden91** [comment]
이렇게 이슈 많이 남겨주시는거 언제나 환영입니다!! 언제든 불편한 점은 이슈 남겨주세요!

폰트크기는 사용자마다 느끼는게 다르기 때문에 해당 부분은 커스터마이징 가능케끔 작업해놓겠습니다 :)

**Comment by itple-sw** [comment]
정말 좋은 스킨 감사합니다~~~ 나중에 스킨 만드는 방법도 배우고 싶습니다~

**Comment by ruden91** [comment]
나중에 스킨 만드는 방법에 대해서 포스팅 하도록 하겠습니다.
스킨 이용해주셔서 감사합니다 :)

이슈들은 시간 날때마다 열심히 처리하겠습니다ㅠㅠ
