### ISSUE TITLE
사이드바 고정 기능

### ISSUE THREAD

**Issue by gamb2t** [ruden91/public-basecamp-skin#22]
현재는 글에 들어가서 스크롤을 내리면 글과 함께 사이드바도 같이 내려가는데
사이드바는 고정되어 있고 글만 내려가게 하는 기능도 추가했으면 좋겠습니다.
글 내용이 길 경우 후반으로 가면 오른쪽 사이드바에 아무것도 표시되지 않아서 약간 허전한 느낌이 들어요.
예쁜 스킨 만들어 주셔서 감사합니다!

**Comment by ruden91** [comment]
사이드바 영역을 고정시키면 사이드바의 길이가 데스크탑 스크린 길이보다 길었을 경우 이슈가 생길 수 있기 때문에 사이드바 내에 원하는 콘텐츠 영역에 한정해서 고정시키는 것을 고려해 보겠습니다!
이용해주셔서 감사합니다!
