### ISSUE TITLE
사이드메뉴의 검색창 사용불가

### ISSUE THREAD

**Issue by aruaru0917** [ruden91/public-basecamp-skin#25]
PC버전 모바일버전 둘다
검색창에 텍스트 입력만 가능하고
텍스트 입력 후 엔터나 검색창 우측의 돋보기 아이콘을 눌러도 검색결과창으로 넘어가지 않습니다!

**Comment by ruden91** [comment]
해당 버그 확인했습니다!
금일 수정사항 반영하겠습니다

**Comment by ruden91** [comment]
1.0.0-rc6에 반영완료했습니다 :)
