### ISSUE TITLE
글 수정, 통계 버튼 추가

### ISSUE THREAD

**Issue by minikupa** [ruden91/public-basecamp-skin#3]
다른 스킨들을 보면 글 내에서 수정 버튼이나 통계 버튼을 눌러 바로 글을 수정하거나 통계를 볼 수 있는 기능을 제공하기도 합니다. 블로그의 관리창에서 글을 찾고 수정 또는 통계를 보는 것은 번거로울 수도 있기에, 해당 기능을 추가해주시면 좋을 것 같습니다.

**Comment by ruden91** [comment]
#4 참고해주세요!
