### ISSUE TITLE
목차 관련하여 건의있습니다.

### ISSUE THREAD

**Issue by ghost** [ruden91/public-basecamp-skin#30]
**안녕하세요.

요 근래 남양주 스킨에 많은 관심이 있어 초기 사용에 있습니다.

이미 이전에 블로그 스킨 댓글에도 남겨놓았지만 깃허브가 오히려 개발자에게 다가가기가 쉬울 것 같아 여기에서도 글을 쓰게 됩니다.

자동 목차 기능도 지원된다는 것이 큰 장점인데 모바일 환경에서도 목차가 작동될 수 있게끔 개선되었으면 좋겠습니다.

사실 목차 기능은 유입되는 인원의 재빠르게 원하는 정보의 영역에만 접근한 뒤, 빠져나가는 것에 큰 의미를 둡니다만 특히 화면이 작은 모바일에서는 원하는 정보의 영역에 접근하기가 여간 까다롭습니다.

제가 생각한 것으로는 좌/우측 상단이나 하단에 아주작은 목차 아이콘을 만들어 그 아이콘을 누르면 목차가 열리는 방식으로 건의드리고 싶습니다.

이제 곧 IOT 와 5G 그리고 그에 걸맞은 스마트 기기의 보급이 더욱더 빨라질터인데 이젠 앉아서 북치고 장구치는 데스크톱 환경은 구시대적인 산물입니다. 이참에 모바일 환경에서도 재빠르게 대응해나갔으면 좋겠습니다.**

**Comment by ruden91** [comment]
좋은 의견 감사합니다 :)
다음 기능 추가 업데이트를 진행할 때 반영하도록 하겠습니다
