### ISSUE TITLE
버그 보고 드립니다.

### ISSUE THREAD

**Issue by ghost** [ruden91/public-basecamp-skin#34]
**1. 티스토리 글 작성 기능 중 "구분선" 을 넣을 시 입력된 구분선 기준 상/하의 단락이 맞지 않는 현상 발생.**

![편집 기능의 구분선 상하 여백](https://user-images.githubusercontent.com/7418669/107333705-309e1700-6af9-11eb-95ac-ec8fff5d101c.png)

**----------------------------구분---------------------------- [위→편집기능의 구분선 상/하 여백]**

![구분선 상하 구분이 되어 있지 않음#1](https://user-images.githubusercontent.com/7418669/107333713-33990780-6af9-11eb-911e-54701d7cb5c1.png)

**----------------------------구분----------------------------[위→게시물에서의 구분선 상/하 여백]**

![모바일  상하 구분이 되어 있지 않음#2](https://user-images.githubusercontent.com/7418669/107333722-34ca3480-6af9-11eb-8008-5f3493d97791.png)

**----------------------------구분----------------------------[위→모바일 게시물에서의 구분선 상/하 여백]**

**Comment by ruden91** [comment]
이슈 감사합니다 :) 확인하고 다음 버전에 바로 반영하겠습니다
