### ISSUE TITLE
안녕하세요. 질문있습니다.

### ISSUE THREAD

**Issue by aprili2140** [ruden91/public-basecamp-skin#45]
1. 소제목인 h2,3태그와, 내용 p태그의 간격이 너무 붙어있어 위 아래 마진을 넣으려고 하는데, 이스킨은 마크다운을 건드려야 하나요? ㅠㅠ p태그 행간은 css에서 바꿧는데.. h태그의 마진 넣는건 할수가 없내요...

마진을 세팅해주실수 있으실까요. h2 위40px 아래20px; /  h3 위30px 아래 15px 이런식으로...

2. 그리고 h2,3 태그에 border를 넣어서 밑줄을 만들거나, 글상자를 만들거나 해서 구분해주고 싶은데 이것도 마크다운건드려야 하는거죠? ㅠㅠ

3. h태그 바로위 광고 뜨게 세팅을 했는데 상단 하단만 광고가 나와서 질문드려요.
 
![1](https://user-images.githubusercontent.com/82647227/115029694-351feb00-9f01-11eb-9b8b-9a7affe5d536.jpg)
![Screenshot 2021-04-16 at 22 13 38](https://user-images.githubusercontent.com/82647227/115029698-35b88180-9f01-11eb-8020-2c8f85990e57.jpg)
![3](https://user-images.githubusercontent.com/82647227/115029820-584a9a80-9f01-11eb-8e70-29423a3b83cc.jpg)

위와같이 세팅했는데 잘못되었나요?

**Comment by ruden91** [comment]
애드센스 광고가 안뜨는 이유는 콘텐츠가 부족해서 광고가 송출이 안될 수 있습니다. 사이트 경로를 알려주시면 정확한 피드백이 가능할 것 같습니다 :)
