### ISSUE TITLE
수고하십니다. 건의 사항이 있습니다.

### ISSUE THREAD

**Issue by Cyp9715** [ruden91/public-basecamp-skin#46]
우선 감사의 말씀 드립니다. 정말 훌륭하고 예쁘게 잘 만들어 주셧어요... 정말 감사하며 사용하고 있습니다.

다름이 아니라 혹여 추 후 시간이 남으시고, 심심하시다면  '다크모드' 에 관해서 추가하실 예정은 없으신가요?

개발자긴 하나, 본업이 웹 개발자가 아닌지라 코드를 건들기 망설여 집니다.. 디자인 적으로 색상 매칭을 못하는 편이기도 하구요.

시간 되실 때 반영해주시면 감사드리겠습니다!

**Comment by ruden91** [comment]
다크모드는 다음 반영에 무조건 넣을 예정입니다 :)
다음 버전에서 우선순위를 둔 기능은 아래와 같습니다
1. 커버
2. 다크모드
3. 커스텀 팝업

아직 많이 부족한 스킨이지만 이렇게 이용해주셔서 감사합니다!
