### ISSUE TITLE
상단바 및 공감, 구독 버튼 가려짐

### ISSUE THREAD

**Issue by minikupa** [ruden91/public-basecamp-skin#9]
![Screenshot_20210120-155925_Whale.jpg](https://user-images.githubusercontent.com/19676242/105138729-a5a0b100-5b38-11eb-893e-d8b06394df03.jpg)
![Screenshot_20210120-155905_Whale.jpg](https://user-images.githubusercontent.com/19676242/105138738-a8030b00-5b38-11eb-88f2-0fec09f02fcb.jpg)

모바일 웨일 사용 중입니다. 위로 드래그하면 상단바가 가려지며, 아래로 드래그 하면 공감, 구독 버튼 등이 가려지네요.

**Comment by minikupa** [comment]
업데이트를 하지 않은 제 블로그에선, 가려짐 없이 잘 나오네요.

**Comment by ruden91** [comment]
오늘 퇴근하고 이부분 체크해보겠습니다 :)

**Comment by minikupa** [comment]
넵 정말 좋은 스킨 만들어주셔서 감사합니다.

**Comment by ruden91** [comment]
![image](https://user-images.githubusercontent.com/13517699/105175899-dba95980-5b67-11eb-9ce0-bfe8f475aea2.png)

갤럭시s10에서 테스트해본 결과 웨일 브라우저에서 해당 증상이 발견되지 않았는데 혹시 디바이스 타입이 어떻게 되시나요?

**Comment by minikupa** [comment]
A51 사용하고 있습니다. 다른 글들도 봤는데, 일부 글을 저렇게 가려지고 일부 글은 잘 나오네요.

글이 좌우로 스크롤 되는 글이 있는데, 해당 글에 가려지는 현상이 나타나는 것 같습니다.

https://webruden.tistory.com/630
이 글은 가려지게 나오네요.

**Comment by ruden91** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/13517699/105179943-4c06a980-5b6d-11eb-97ac-78246bd8675b.gif)

페이지네이션 영역 넘어가는 부분 개선했는데 아직도 해당 증상이 발생하시나요?

**Comment by minikupa** [comment]
아뇨 이제 잘 보입니다. 감사합니다.
